./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype1 -e -1>>./Data/Real_Data/Quartets/C/Results1.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype2 -e -1>>./Data/Real_Data/Quartets/C/Results2.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype3 -e -1>>./Data/Real_Data/Quartets/C/Results3.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype4 -e -1>>./Data/Real_Data/Quartets/C/Results4.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype5 -e -1>>./Data/Real_Data/Quartets/C/Results5.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype6 -e -1>>./Data/Real_Data/Quartets/C/Results6.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype7 -e -1>>./Data/Real_Data/Quartets/C/Results7.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype8 -e -1>>./Data/Real_Data/Quartets/C/Results8.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype9 -e -1>>./Data/Real_Data/Quartets/C/Results9.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype10 -e -1>>./Data/Real_Data/Quartets/C/Results10.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype11 -e -1>>./Data/Real_Data/Quartets/C/Results11.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype12 -e -1>>./Data/Real_Data/Quartets/C/Results12.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype13 -e -1>>./Data/Real_Data/Quartets/C/Results13.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype14 -e -1>>./Data/Real_Data/Quartets/C/Results14.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype15 -e -1>>./Data/Real_Data/Quartets/C/Results15.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype16 -e -1>>./Data/Real_Data/Quartets/C/Results16.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype17 -e -1>>./Data/Real_Data/Quartets/C/Results17.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype18 -e -1>>./Data/Real_Data/Quartets/C/Results18.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype19 -e -1>>./Data/Real_Data/Quartets/C/Results19.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype20 -e -1>>./Data/Real_Data/Quartets/C/Results20.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype21 -e -1>>./Data/Real_Data/Quartets/C/Results21.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype22 -e -1>>./Data/Real_Data/Quartets/C/Results22.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype23 -e -1>>./Data/Real_Data/Quartets/C/Results23.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype24 -e -1>>./Data/Real_Data/Quartets/C/Results24.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype25 -e -1>>./Data/Real_Data/Quartets/C/Results25.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype26 -e -1>>./Data/Real_Data/Quartets/C/Results26.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype27 -e -1>>./Data/Real_Data/Quartets/C/Results27.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype28 -e -1>>./Data/Real_Data/Quartets/C/Results28.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype29 -e -1>>./Data/Real_Data/Quartets/C/Results29.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype30 -e -1>>./Data/Real_Data/Quartets/C/Results30.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype31 -e -1>>./Data/Real_Data/Quartets/C/Results31.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype32 -e -1>>./Data/Real_Data/Quartets/C/Results32.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype33 -e -1>>./Data/Real_Data/Quartets/C/Results33.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype34 -e -1>>./Data/Real_Data/Quartets/C/Results34.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype35 -e -1>>./Data/Real_Data/Quartets/C/Results35.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype36 -e -1>>./Data/Real_Data/Quartets/C/Results36.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype37 -e -1>>./Data/Real_Data/Quartets/C/Results37.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype38 -e -1>>./Data/Real_Data/Quartets/C/Results38.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype39 -e -1>>./Data/Real_Data/Quartets/C/Results39.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype40 -e -1>>./Data/Real_Data/Quartets/C/Results40.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype41 -e -1>>./Data/Real_Data/Quartets/C/Results41.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype42 -e -1>>./Data/Real_Data/Quartets/C/Results42.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype43 -e -1>>./Data/Real_Data/Quartets/C/Results43.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype44 -e -1>>./Data/Real_Data/Quartets/C/Results44.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype45 -e -1>>./Data/Real_Data/Quartets/C/Results45.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype46 -e -1>>./Data/Real_Data/Quartets/C/Results46.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype47 -e -1>>./Data/Real_Data/Quartets/C/Results47.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype48 -e -1>>./Data/Real_Data/Quartets/C/Results48.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype49 -e -1>>./Data/Real_Data/Quartets/C/Results49.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype50 -e -1>>./Data/Real_Data/Quartets/C/Results50.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype51 -e -1>>./Data/Real_Data/Quartets/C/Results51.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype52 -e -1>>./Data/Real_Data/Quartets/C/Results52.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype53 -e -1>>./Data/Real_Data/Quartets/C/Results53.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype54 -e -1>>./Data/Real_Data/Quartets/C/Results54.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype55 -e -1>>./Data/Real_Data/Quartets/C/Results55.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype56 -e -1>>./Data/Real_Data/Quartets/C/Results56.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype57 -e -1>>./Data/Real_Data/Quartets/C/Results57.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype58 -e -1>>./Data/Real_Data/Quartets/C/Results58.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype59 -e -1>>./Data/Real_Data/Quartets/C/Results59.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype60 -e -1>>./Data/Real_Data/Quartets/C/Results60.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype61 -e -1>>./Data/Real_Data/Quartets/C/Results61.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype62 -e -1>>./Data/Real_Data/Quartets/C/Results62.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype63 -e -1>>./Data/Real_Data/Quartets/C/Results63.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype64 -e -1>>./Data/Real_Data/Quartets/C/Results64.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype65 -e -1>>./Data/Real_Data/Quartets/C/Results65.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype66 -e -1>>./Data/Real_Data/Quartets/C/Results66.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype67 -e -1>>./Data/Real_Data/Quartets/C/Results67.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype68 -e -1>>./Data/Real_Data/Quartets/C/Results68.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype69 -e -1>>./Data/Real_Data/Quartets/C/Results69.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype70 -e -1>>./Data/Real_Data/Quartets/C/Results70.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype71 -e -1>>./Data/Real_Data/Quartets/C/Results71.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype72 -e -1>>./Data/Real_Data/Quartets/C/Results72.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype73 -e -1>>./Data/Real_Data/Quartets/C/Results73.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype74 -e -1>>./Data/Real_Data/Quartets/C/Results74.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype75 -e -1>>./Data/Real_Data/Quartets/C/Results75.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype76 -e -1>>./Data/Real_Data/Quartets/C/Results76.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype77 -e -1>>./Data/Real_Data/Quartets/C/Results77.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype78 -e -1>>./Data/Real_Data/Quartets/C/Results78.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype79 -e -1>>./Data/Real_Data/Quartets/C/Results79.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype80 -e -1>>./Data/Real_Data/Quartets/C/Results80.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype81 -e -1>>./Data/Real_Data/Quartets/C/Results81.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype82 -e -1>>./Data/Real_Data/Quartets/C/Results82.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype83 -e -1>>./Data/Real_Data/Quartets/C/Results83.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype84 -e -1>>./Data/Real_Data/Quartets/C/Results84.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype85 -e -1>>./Data/Real_Data/Quartets/C/Results85.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype86 -e -1>>./Data/Real_Data/Quartets/C/Results86.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype87 -e -1>>./Data/Real_Data/Quartets/C/Results87.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype88 -e -1>>./Data/Real_Data/Quartets/C/Results88.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype89 -e -1>>./Data/Real_Data/Quartets/C/Results89.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype90 -e -1>>./Data/Real_Data/Quartets/C/Results90.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype91 -e -1>>./Data/Real_Data/Quartets/C/Results91.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype92 -e -1>>./Data/Real_Data/Quartets/C/Results92.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype93 -e -1>>./Data/Real_Data/Quartets/C/Results93.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype94 -e -1>>./Data/Real_Data/Quartets/C/Results94.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype95 -e -1>>./Data/Real_Data/Quartets/C/Results95.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype96 -e -1>>./Data/Real_Data/Quartets/C/Results96.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype97 -e -1>>./Data/Real_Data/Quartets/C/Results97.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype98 -e -1>>./Data/Real_Data/Quartets/C/Results98.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype99 -e -1>>./Data/Real_Data/Quartets/C/Results99.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype100 -e -1>>./Data/Real_Data/Quartets/C/Results100.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype101 -e -1>>./Data/Real_Data/Quartets/C/Results101.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype102 -e -1>>./Data/Real_Data/Quartets/C/Results102.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype103 -e -1>>./Data/Real_Data/Quartets/C/Results103.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype104 -e -1>>./Data/Real_Data/Quartets/C/Results104.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype105 -e -1>>./Data/Real_Data/Quartets/C/Results105.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype106 -e -1>>./Data/Real_Data/Quartets/C/Results106.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype107 -e -1>>./Data/Real_Data/Quartets/C/Results107.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype108 -e -1>>./Data/Real_Data/Quartets/C/Results108.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype109 -e -1>>./Data/Real_Data/Quartets/C/Results109.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype110 -e -1>>./Data/Real_Data/Quartets/C/Results110.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype111 -e -1>>./Data/Real_Data/Quartets/C/Results111.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype112 -e -1>>./Data/Real_Data/Quartets/C/Results112.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype113 -e -1>>./Data/Real_Data/Quartets/C/Results113.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype114 -e -1>>./Data/Real_Data/Quartets/C/Results114.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype115 -e -1>>./Data/Real_Data/Quartets/C/Results115.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype116 -e -1>>./Data/Real_Data/Quartets/C/Results116.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype117 -e -1>>./Data/Real_Data/Quartets/C/Results117.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype118 -e -1>>./Data/Real_Data/Quartets/C/Results118.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype119 -e -1>>./Data/Real_Data/Quartets/C/Results119.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype120 -e -1>>./Data/Real_Data/Quartets/C/Results120.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype121 -e -1>>./Data/Real_Data/Quartets/C/Results121.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype122 -e -1>>./Data/Real_Data/Quartets/C/Results122.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype123 -e -1>>./Data/Real_Data/Quartets/C/Results123.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype124 -e -1>>./Data/Real_Data/Quartets/C/Results124.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype125 -e -1>>./Data/Real_Data/Quartets/C/Results125.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype126 -e -1>>./Data/Real_Data/Quartets/C/Results126.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype127 -e -1>>./Data/Real_Data/Quartets/C/Results127.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype128 -e -1>>./Data/Real_Data/Quartets/C/Results128.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype129 -e -1>>./Data/Real_Data/Quartets/C/Results129.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype130 -e -1>>./Data/Real_Data/Quartets/C/Results130.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype131 -e -1>>./Data/Real_Data/Quartets/C/Results131.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype132 -e -1>>./Data/Real_Data/Quartets/C/Results132.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype133 -e -1>>./Data/Real_Data/Quartets/C/Results133.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype134 -e -1>>./Data/Real_Data/Quartets/C/Results134.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype135 -e -1>>./Data/Real_Data/Quartets/C/Results135.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype136 -e -1>>./Data/Real_Data/Quartets/C/Results136.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype137 -e -1>>./Data/Real_Data/Quartets/C/Results137.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype138 -e -1>>./Data/Real_Data/Quartets/C/Results138.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype139 -e -1>>./Data/Real_Data/Quartets/C/Results139.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype140 -e -1>>./Data/Real_Data/Quartets/C/Results140.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype141 -e -1>>./Data/Real_Data/Quartets/C/Results141.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype142 -e -1>>./Data/Real_Data/Quartets/C/Results142.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype143 -e -1>>./Data/Real_Data/Quartets/C/Results143.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype144 -e -1>>./Data/Real_Data/Quartets/C/Results144.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype145 -e -1>>./Data/Real_Data/Quartets/C/Results145.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype146 -e -1>>./Data/Real_Data/Quartets/C/Results146.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype147 -e -1>>./Data/Real_Data/Quartets/C/Results147.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype148 -e -1>>./Data/Real_Data/Quartets/C/Results148.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype149 -e -1>>./Data/Real_Data/Quartets/C/Results149.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype150 -e -1>>./Data/Real_Data/Quartets/C/Results150.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype151 -e -1>>./Data/Real_Data/Quartets/C/Results151.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype152 -e -1>>./Data/Real_Data/Quartets/C/Results152.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype153 -e -1>>./Data/Real_Data/Quartets/C/Results153.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype154 -e -1>>./Data/Real_Data/Quartets/C/Results154.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype155 -e -1>>./Data/Real_Data/Quartets/C/Results155.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype156 -e -1>>./Data/Real_Data/Quartets/C/Results156.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype157 -e -1>>./Data/Real_Data/Quartets/C/Results157.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype158 -e -1>>./Data/Real_Data/Quartets/C/Results158.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype159 -e -1>>./Data/Real_Data/Quartets/C/Results159.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype160 -e -1>>./Data/Real_Data/Quartets/C/Results160.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype161 -e -1>>./Data/Real_Data/Quartets/C/Results161.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype162 -e -1>>./Data/Real_Data/Quartets/C/Results162.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype163 -e -1>>./Data/Real_Data/Quartets/C/Results163.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype164 -e -1>>./Data/Real_Data/Quartets/C/Results164.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype165 -e -1>>./Data/Real_Data/Quartets/C/Results165.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype166 -e -1>>./Data/Real_Data/Quartets/C/Results166.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype167 -e -1>>./Data/Real_Data/Quartets/C/Results167.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype168 -e -1>>./Data/Real_Data/Quartets/C/Results168.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype169 -e -1>>./Data/Real_Data/Quartets/C/Results169.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype170 -e -1>>./Data/Real_Data/Quartets/C/Results170.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype171 -e -1>>./Data/Real_Data/Quartets/C/Results171.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype172 -e -1>>./Data/Real_Data/Quartets/C/Results172.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype173 -e -1>>./Data/Real_Data/Quartets/C/Results173.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype174 -e -1>>./Data/Real_Data/Quartets/C/Results174.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype175 -e -1>>./Data/Real_Data/Quartets/C/Results175.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype176 -e -1>>./Data/Real_Data/Quartets/C/Results176.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype177 -e -1>>./Data/Real_Data/Quartets/C/Results177.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype178 -e -1>>./Data/Real_Data/Quartets/C/Results178.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype179 -e -1>>./Data/Real_Data/Quartets/C/Results179.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype180 -e -1>>./Data/Real_Data/Quartets/C/Results180.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype181 -e -1>>./Data/Real_Data/Quartets/C/Results181.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype182 -e -1>>./Data/Real_Data/Quartets/C/Results182.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype183 -e -1>>./Data/Real_Data/Quartets/C/Results183.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype184 -e -1>>./Data/Real_Data/Quartets/C/Results184.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype185 -e -1>>./Data/Real_Data/Quartets/C/Results185.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype186 -e -1>>./Data/Real_Data/Quartets/C/Results186.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype187 -e -1>>./Data/Real_Data/Quartets/C/Results187.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype188 -e -1>>./Data/Real_Data/Quartets/C/Results188.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype189 -e -1>>./Data/Real_Data/Quartets/C/Results189.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype190 -e -1>>./Data/Real_Data/Quartets/C/Results190.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype191 -e -1>>./Data/Real_Data/Quartets/C/Results191.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype192 -e -1>>./Data/Real_Data/Quartets/C/Results192.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype193 -e -1>>./Data/Real_Data/Quartets/C/Results193.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype194 -e -1>>./Data/Real_Data/Quartets/C/Results194.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype195 -e -1>>./Data/Real_Data/Quartets/C/Results195.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype196 -e -1>>./Data/Real_Data/Quartets/C/Results196.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype197 -e -1>>./Data/Real_Data/Quartets/C/Results197.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype198 -e -1>>./Data/Real_Data/Quartets/C/Results198.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype199 -e -1>>./Data/Real_Data/Quartets/C/Results199.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype200 -e -1>>./Data/Real_Data/Quartets/C/Results200.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype201 -e -1>>./Data/Real_Data/Quartets/C/Results201.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype202 -e -1>>./Data/Real_Data/Quartets/C/Results202.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype203 -e -1>>./Data/Real_Data/Quartets/C/Results203.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype204 -e -1>>./Data/Real_Data/Quartets/C/Results204.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype205 -e -1>>./Data/Real_Data/Quartets/C/Results205.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype206 -e -1>>./Data/Real_Data/Quartets/C/Results206.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype207 -e -1>>./Data/Real_Data/Quartets/C/Results207.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype208 -e -1>>./Data/Real_Data/Quartets/C/Results208.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype209 -e -1>>./Data/Real_Data/Quartets/C/Results209.dat
./ct-cbn-0.1.04b/ct-cbn -f ./Data/Real_Data/Quartets/C/Genotype210 -e -1>>./Data/Real_Data/Quartets/C/Results210.dat
