mkdir ./Data/Real_Data/Quartets/C/Genotype1
echo '4'>>./Data/Real_Data/Quartets/C/Genotype1.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype1.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype1
mkdir ./Data/Real_Data/Quartets/R/Genotype1
mkdir ./Data/Real_Data/Quartets/C/Genotype2
echo '4'>>./Data/Real_Data/Quartets/C/Genotype2.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype2.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype2
mkdir ./Data/Real_Data/Quartets/R/Genotype2
mkdir ./Data/Real_Data/Quartets/C/Genotype3
echo '4'>>./Data/Real_Data/Quartets/C/Genotype3.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype3.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype3
mkdir ./Data/Real_Data/Quartets/R/Genotype3
mkdir ./Data/Real_Data/Quartets/C/Genotype4
echo '4'>>./Data/Real_Data/Quartets/C/Genotype4.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype4.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype4
mkdir ./Data/Real_Data/Quartets/R/Genotype4
mkdir ./Data/Real_Data/Quartets/C/Genotype5
echo '4'>>./Data/Real_Data/Quartets/C/Genotype5.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype5.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype5
mkdir ./Data/Real_Data/Quartets/R/Genotype5
mkdir ./Data/Real_Data/Quartets/C/Genotype6
echo '4'>>./Data/Real_Data/Quartets/C/Genotype6.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype6.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype6
mkdir ./Data/Real_Data/Quartets/R/Genotype6
mkdir ./Data/Real_Data/Quartets/C/Genotype7
echo '4'>>./Data/Real_Data/Quartets/C/Genotype7.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype7.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype7
mkdir ./Data/Real_Data/Quartets/R/Genotype7
mkdir ./Data/Real_Data/Quartets/C/Genotype8
echo '4'>>./Data/Real_Data/Quartets/C/Genotype8.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype8.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype8
mkdir ./Data/Real_Data/Quartets/R/Genotype8
mkdir ./Data/Real_Data/Quartets/C/Genotype9
echo '4'>>./Data/Real_Data/Quartets/C/Genotype9.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype9.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype9
mkdir ./Data/Real_Data/Quartets/R/Genotype9
mkdir ./Data/Real_Data/Quartets/C/Genotype10
echo '4'>>./Data/Real_Data/Quartets/C/Genotype10.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype10.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype10
mkdir ./Data/Real_Data/Quartets/R/Genotype10
mkdir ./Data/Real_Data/Quartets/C/Genotype11
echo '4'>>./Data/Real_Data/Quartets/C/Genotype11.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype11.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype11
mkdir ./Data/Real_Data/Quartets/R/Genotype11
mkdir ./Data/Real_Data/Quartets/C/Genotype12
echo '4'>>./Data/Real_Data/Quartets/C/Genotype12.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype12.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype12
mkdir ./Data/Real_Data/Quartets/R/Genotype12
mkdir ./Data/Real_Data/Quartets/C/Genotype13
echo '4'>>./Data/Real_Data/Quartets/C/Genotype13.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype13.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype13
mkdir ./Data/Real_Data/Quartets/R/Genotype13
mkdir ./Data/Real_Data/Quartets/C/Genotype14
echo '4'>>./Data/Real_Data/Quartets/C/Genotype14.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype14.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype14
mkdir ./Data/Real_Data/Quartets/R/Genotype14
mkdir ./Data/Real_Data/Quartets/C/Genotype15
echo '4'>>./Data/Real_Data/Quartets/C/Genotype15.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype15.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype15
mkdir ./Data/Real_Data/Quartets/R/Genotype15
mkdir ./Data/Real_Data/Quartets/C/Genotype16
echo '4'>>./Data/Real_Data/Quartets/C/Genotype16.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype16.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype16
mkdir ./Data/Real_Data/Quartets/R/Genotype16
mkdir ./Data/Real_Data/Quartets/C/Genotype17
echo '4'>>./Data/Real_Data/Quartets/C/Genotype17.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype17.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype17
mkdir ./Data/Real_Data/Quartets/R/Genotype17
mkdir ./Data/Real_Data/Quartets/C/Genotype18
echo '4'>>./Data/Real_Data/Quartets/C/Genotype18.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype18.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype18
mkdir ./Data/Real_Data/Quartets/R/Genotype18
mkdir ./Data/Real_Data/Quartets/C/Genotype19
echo '4'>>./Data/Real_Data/Quartets/C/Genotype19.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype19.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype19
mkdir ./Data/Real_Data/Quartets/R/Genotype19
mkdir ./Data/Real_Data/Quartets/C/Genotype20
echo '4'>>./Data/Real_Data/Quartets/C/Genotype20.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype20.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype20
mkdir ./Data/Real_Data/Quartets/R/Genotype20
mkdir ./Data/Real_Data/Quartets/C/Genotype21
echo '4'>>./Data/Real_Data/Quartets/C/Genotype21.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype21.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype21
mkdir ./Data/Real_Data/Quartets/R/Genotype21
mkdir ./Data/Real_Data/Quartets/C/Genotype22
echo '4'>>./Data/Real_Data/Quartets/C/Genotype22.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype22.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype22
mkdir ./Data/Real_Data/Quartets/R/Genotype22
mkdir ./Data/Real_Data/Quartets/C/Genotype23
echo '4'>>./Data/Real_Data/Quartets/C/Genotype23.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype23.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype23
mkdir ./Data/Real_Data/Quartets/R/Genotype23
mkdir ./Data/Real_Data/Quartets/C/Genotype24
echo '4'>>./Data/Real_Data/Quartets/C/Genotype24.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype24.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype24
mkdir ./Data/Real_Data/Quartets/R/Genotype24
mkdir ./Data/Real_Data/Quartets/C/Genotype25
echo '4'>>./Data/Real_Data/Quartets/C/Genotype25.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype25.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype25
mkdir ./Data/Real_Data/Quartets/R/Genotype25
mkdir ./Data/Real_Data/Quartets/C/Genotype26
echo '4'>>./Data/Real_Data/Quartets/C/Genotype26.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype26.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype26
mkdir ./Data/Real_Data/Quartets/R/Genotype26
mkdir ./Data/Real_Data/Quartets/C/Genotype27
echo '4'>>./Data/Real_Data/Quartets/C/Genotype27.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype27.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype27
mkdir ./Data/Real_Data/Quartets/R/Genotype27
mkdir ./Data/Real_Data/Quartets/C/Genotype28
echo '4'>>./Data/Real_Data/Quartets/C/Genotype28.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype28.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype28
mkdir ./Data/Real_Data/Quartets/R/Genotype28
mkdir ./Data/Real_Data/Quartets/C/Genotype29
echo '4'>>./Data/Real_Data/Quartets/C/Genotype29.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype29.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype29
mkdir ./Data/Real_Data/Quartets/R/Genotype29
mkdir ./Data/Real_Data/Quartets/C/Genotype30
echo '4'>>./Data/Real_Data/Quartets/C/Genotype30.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype30.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype30
mkdir ./Data/Real_Data/Quartets/R/Genotype30
mkdir ./Data/Real_Data/Quartets/C/Genotype31
echo '4'>>./Data/Real_Data/Quartets/C/Genotype31.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype31.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype31
mkdir ./Data/Real_Data/Quartets/R/Genotype31
mkdir ./Data/Real_Data/Quartets/C/Genotype32
echo '4'>>./Data/Real_Data/Quartets/C/Genotype32.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype32.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype32
mkdir ./Data/Real_Data/Quartets/R/Genotype32
mkdir ./Data/Real_Data/Quartets/C/Genotype33
echo '4'>>./Data/Real_Data/Quartets/C/Genotype33.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype33.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype33
mkdir ./Data/Real_Data/Quartets/R/Genotype33
mkdir ./Data/Real_Data/Quartets/C/Genotype34
echo '4'>>./Data/Real_Data/Quartets/C/Genotype34.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype34.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype34
mkdir ./Data/Real_Data/Quartets/R/Genotype34
mkdir ./Data/Real_Data/Quartets/C/Genotype35
echo '4'>>./Data/Real_Data/Quartets/C/Genotype35.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype35.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype35
mkdir ./Data/Real_Data/Quartets/R/Genotype35
mkdir ./Data/Real_Data/Quartets/C/Genotype36
echo '4'>>./Data/Real_Data/Quartets/C/Genotype36.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype36.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype36
mkdir ./Data/Real_Data/Quartets/R/Genotype36
mkdir ./Data/Real_Data/Quartets/C/Genotype37
echo '4'>>./Data/Real_Data/Quartets/C/Genotype37.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype37.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype37
mkdir ./Data/Real_Data/Quartets/R/Genotype37
mkdir ./Data/Real_Data/Quartets/C/Genotype38
echo '4'>>./Data/Real_Data/Quartets/C/Genotype38.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype38.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype38
mkdir ./Data/Real_Data/Quartets/R/Genotype38
mkdir ./Data/Real_Data/Quartets/C/Genotype39
echo '4'>>./Data/Real_Data/Quartets/C/Genotype39.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype39.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype39
mkdir ./Data/Real_Data/Quartets/R/Genotype39
mkdir ./Data/Real_Data/Quartets/C/Genotype40
echo '4'>>./Data/Real_Data/Quartets/C/Genotype40.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype40.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype40
mkdir ./Data/Real_Data/Quartets/R/Genotype40
mkdir ./Data/Real_Data/Quartets/C/Genotype41
echo '4'>>./Data/Real_Data/Quartets/C/Genotype41.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype41.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype41
mkdir ./Data/Real_Data/Quartets/R/Genotype41
mkdir ./Data/Real_Data/Quartets/C/Genotype42
echo '4'>>./Data/Real_Data/Quartets/C/Genotype42.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype42.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype42
mkdir ./Data/Real_Data/Quartets/R/Genotype42
mkdir ./Data/Real_Data/Quartets/C/Genotype43
echo '4'>>./Data/Real_Data/Quartets/C/Genotype43.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype43.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype43
mkdir ./Data/Real_Data/Quartets/R/Genotype43
mkdir ./Data/Real_Data/Quartets/C/Genotype44
echo '4'>>./Data/Real_Data/Quartets/C/Genotype44.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype44.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype44
mkdir ./Data/Real_Data/Quartets/R/Genotype44
mkdir ./Data/Real_Data/Quartets/C/Genotype45
echo '4'>>./Data/Real_Data/Quartets/C/Genotype45.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype45.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype45
mkdir ./Data/Real_Data/Quartets/R/Genotype45
mkdir ./Data/Real_Data/Quartets/C/Genotype46
echo '4'>>./Data/Real_Data/Quartets/C/Genotype46.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype46.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype46
mkdir ./Data/Real_Data/Quartets/R/Genotype46
mkdir ./Data/Real_Data/Quartets/C/Genotype47
echo '4'>>./Data/Real_Data/Quartets/C/Genotype47.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype47.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype47
mkdir ./Data/Real_Data/Quartets/R/Genotype47
mkdir ./Data/Real_Data/Quartets/C/Genotype48
echo '4'>>./Data/Real_Data/Quartets/C/Genotype48.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype48.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype48
mkdir ./Data/Real_Data/Quartets/R/Genotype48
mkdir ./Data/Real_Data/Quartets/C/Genotype49
echo '4'>>./Data/Real_Data/Quartets/C/Genotype49.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype49.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype49
mkdir ./Data/Real_Data/Quartets/R/Genotype49
mkdir ./Data/Real_Data/Quartets/C/Genotype50
echo '4'>>./Data/Real_Data/Quartets/C/Genotype50.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype50.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype50
mkdir ./Data/Real_Data/Quartets/R/Genotype50
mkdir ./Data/Real_Data/Quartets/C/Genotype51
echo '4'>>./Data/Real_Data/Quartets/C/Genotype51.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype51.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype51
mkdir ./Data/Real_Data/Quartets/R/Genotype51
mkdir ./Data/Real_Data/Quartets/C/Genotype52
echo '4'>>./Data/Real_Data/Quartets/C/Genotype52.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype52.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype52
mkdir ./Data/Real_Data/Quartets/R/Genotype52
mkdir ./Data/Real_Data/Quartets/C/Genotype53
echo '4'>>./Data/Real_Data/Quartets/C/Genotype53.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype53.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype53
mkdir ./Data/Real_Data/Quartets/R/Genotype53
mkdir ./Data/Real_Data/Quartets/C/Genotype54
echo '4'>>./Data/Real_Data/Quartets/C/Genotype54.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype54.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype54
mkdir ./Data/Real_Data/Quartets/R/Genotype54
mkdir ./Data/Real_Data/Quartets/C/Genotype55
echo '4'>>./Data/Real_Data/Quartets/C/Genotype55.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype55.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype55
mkdir ./Data/Real_Data/Quartets/R/Genotype55
mkdir ./Data/Real_Data/Quartets/C/Genotype56
echo '4'>>./Data/Real_Data/Quartets/C/Genotype56.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype56.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype56
mkdir ./Data/Real_Data/Quartets/R/Genotype56
mkdir ./Data/Real_Data/Quartets/C/Genotype57
echo '4'>>./Data/Real_Data/Quartets/C/Genotype57.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype57.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype57
mkdir ./Data/Real_Data/Quartets/R/Genotype57
mkdir ./Data/Real_Data/Quartets/C/Genotype58
echo '4'>>./Data/Real_Data/Quartets/C/Genotype58.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype58.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype58
mkdir ./Data/Real_Data/Quartets/R/Genotype58
mkdir ./Data/Real_Data/Quartets/C/Genotype59
echo '4'>>./Data/Real_Data/Quartets/C/Genotype59.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype59.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype59
mkdir ./Data/Real_Data/Quartets/R/Genotype59
mkdir ./Data/Real_Data/Quartets/C/Genotype60
echo '4'>>./Data/Real_Data/Quartets/C/Genotype60.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype60.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype60
mkdir ./Data/Real_Data/Quartets/R/Genotype60
mkdir ./Data/Real_Data/Quartets/C/Genotype61
echo '4'>>./Data/Real_Data/Quartets/C/Genotype61.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype61.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype61
mkdir ./Data/Real_Data/Quartets/R/Genotype61
mkdir ./Data/Real_Data/Quartets/C/Genotype62
echo '4'>>./Data/Real_Data/Quartets/C/Genotype62.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype62.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype62
mkdir ./Data/Real_Data/Quartets/R/Genotype62
mkdir ./Data/Real_Data/Quartets/C/Genotype63
echo '4'>>./Data/Real_Data/Quartets/C/Genotype63.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype63.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype63
mkdir ./Data/Real_Data/Quartets/R/Genotype63
mkdir ./Data/Real_Data/Quartets/C/Genotype64
echo '4'>>./Data/Real_Data/Quartets/C/Genotype64.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype64.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype64
mkdir ./Data/Real_Data/Quartets/R/Genotype64
mkdir ./Data/Real_Data/Quartets/C/Genotype65
echo '4'>>./Data/Real_Data/Quartets/C/Genotype65.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype65.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype65
mkdir ./Data/Real_Data/Quartets/R/Genotype65
mkdir ./Data/Real_Data/Quartets/C/Genotype66
echo '4'>>./Data/Real_Data/Quartets/C/Genotype66.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype66.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype66
mkdir ./Data/Real_Data/Quartets/R/Genotype66
mkdir ./Data/Real_Data/Quartets/C/Genotype67
echo '4'>>./Data/Real_Data/Quartets/C/Genotype67.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype67.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype67
mkdir ./Data/Real_Data/Quartets/R/Genotype67
mkdir ./Data/Real_Data/Quartets/C/Genotype68
echo '4'>>./Data/Real_Data/Quartets/C/Genotype68.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype68.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype68
mkdir ./Data/Real_Data/Quartets/R/Genotype68
mkdir ./Data/Real_Data/Quartets/C/Genotype69
echo '4'>>./Data/Real_Data/Quartets/C/Genotype69.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype69.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype69
mkdir ./Data/Real_Data/Quartets/R/Genotype69
mkdir ./Data/Real_Data/Quartets/C/Genotype70
echo '4'>>./Data/Real_Data/Quartets/C/Genotype70.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype70.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype70
mkdir ./Data/Real_Data/Quartets/R/Genotype70
mkdir ./Data/Real_Data/Quartets/C/Genotype71
echo '4'>>./Data/Real_Data/Quartets/C/Genotype71.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype71.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype71
mkdir ./Data/Real_Data/Quartets/R/Genotype71
mkdir ./Data/Real_Data/Quartets/C/Genotype72
echo '4'>>./Data/Real_Data/Quartets/C/Genotype72.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype72.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype72
mkdir ./Data/Real_Data/Quartets/R/Genotype72
mkdir ./Data/Real_Data/Quartets/C/Genotype73
echo '4'>>./Data/Real_Data/Quartets/C/Genotype73.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype73.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype73
mkdir ./Data/Real_Data/Quartets/R/Genotype73
mkdir ./Data/Real_Data/Quartets/C/Genotype74
echo '4'>>./Data/Real_Data/Quartets/C/Genotype74.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype74.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype74
mkdir ./Data/Real_Data/Quartets/R/Genotype74
mkdir ./Data/Real_Data/Quartets/C/Genotype75
echo '4'>>./Data/Real_Data/Quartets/C/Genotype75.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype75.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype75
mkdir ./Data/Real_Data/Quartets/R/Genotype75
mkdir ./Data/Real_Data/Quartets/C/Genotype76
echo '4'>>./Data/Real_Data/Quartets/C/Genotype76.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype76.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype76
mkdir ./Data/Real_Data/Quartets/R/Genotype76
mkdir ./Data/Real_Data/Quartets/C/Genotype77
echo '4'>>./Data/Real_Data/Quartets/C/Genotype77.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype77.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype77
mkdir ./Data/Real_Data/Quartets/R/Genotype77
mkdir ./Data/Real_Data/Quartets/C/Genotype78
echo '4'>>./Data/Real_Data/Quartets/C/Genotype78.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype78.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype78
mkdir ./Data/Real_Data/Quartets/R/Genotype78
mkdir ./Data/Real_Data/Quartets/C/Genotype79
echo '4'>>./Data/Real_Data/Quartets/C/Genotype79.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype79.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype79
mkdir ./Data/Real_Data/Quartets/R/Genotype79
mkdir ./Data/Real_Data/Quartets/C/Genotype80
echo '4'>>./Data/Real_Data/Quartets/C/Genotype80.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype80.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype80
mkdir ./Data/Real_Data/Quartets/R/Genotype80
mkdir ./Data/Real_Data/Quartets/C/Genotype81
echo '4'>>./Data/Real_Data/Quartets/C/Genotype81.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype81.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype81
mkdir ./Data/Real_Data/Quartets/R/Genotype81
mkdir ./Data/Real_Data/Quartets/C/Genotype82
echo '4'>>./Data/Real_Data/Quartets/C/Genotype82.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype82.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype82
mkdir ./Data/Real_Data/Quartets/R/Genotype82
mkdir ./Data/Real_Data/Quartets/C/Genotype83
echo '4'>>./Data/Real_Data/Quartets/C/Genotype83.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype83.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype83
mkdir ./Data/Real_Data/Quartets/R/Genotype83
mkdir ./Data/Real_Data/Quartets/C/Genotype84
echo '4'>>./Data/Real_Data/Quartets/C/Genotype84.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype84.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype84
mkdir ./Data/Real_Data/Quartets/R/Genotype84
mkdir ./Data/Real_Data/Quartets/C/Genotype85
echo '4'>>./Data/Real_Data/Quartets/C/Genotype85.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype85.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype85
mkdir ./Data/Real_Data/Quartets/R/Genotype85
mkdir ./Data/Real_Data/Quartets/C/Genotype86
echo '4'>>./Data/Real_Data/Quartets/C/Genotype86.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype86.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype86
mkdir ./Data/Real_Data/Quartets/R/Genotype86
mkdir ./Data/Real_Data/Quartets/C/Genotype87
echo '4'>>./Data/Real_Data/Quartets/C/Genotype87.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype87.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype87
mkdir ./Data/Real_Data/Quartets/R/Genotype87
mkdir ./Data/Real_Data/Quartets/C/Genotype88
echo '4'>>./Data/Real_Data/Quartets/C/Genotype88.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype88.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype88
mkdir ./Data/Real_Data/Quartets/R/Genotype88
mkdir ./Data/Real_Data/Quartets/C/Genotype89
echo '4'>>./Data/Real_Data/Quartets/C/Genotype89.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype89.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype89
mkdir ./Data/Real_Data/Quartets/R/Genotype89
mkdir ./Data/Real_Data/Quartets/C/Genotype90
echo '4'>>./Data/Real_Data/Quartets/C/Genotype90.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype90.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype90
mkdir ./Data/Real_Data/Quartets/R/Genotype90
mkdir ./Data/Real_Data/Quartets/C/Genotype91
echo '4'>>./Data/Real_Data/Quartets/C/Genotype91.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype91.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype91
mkdir ./Data/Real_Data/Quartets/R/Genotype91
mkdir ./Data/Real_Data/Quartets/C/Genotype92
echo '4'>>./Data/Real_Data/Quartets/C/Genotype92.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype92.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype92
mkdir ./Data/Real_Data/Quartets/R/Genotype92
mkdir ./Data/Real_Data/Quartets/C/Genotype93
echo '4'>>./Data/Real_Data/Quartets/C/Genotype93.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype93.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype93
mkdir ./Data/Real_Data/Quartets/R/Genotype93
mkdir ./Data/Real_Data/Quartets/C/Genotype94
echo '4'>>./Data/Real_Data/Quartets/C/Genotype94.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype94.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype94
mkdir ./Data/Real_Data/Quartets/R/Genotype94
mkdir ./Data/Real_Data/Quartets/C/Genotype95
echo '4'>>./Data/Real_Data/Quartets/C/Genotype95.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype95.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype95
mkdir ./Data/Real_Data/Quartets/R/Genotype95
mkdir ./Data/Real_Data/Quartets/C/Genotype96
echo '4'>>./Data/Real_Data/Quartets/C/Genotype96.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype96.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype96
mkdir ./Data/Real_Data/Quartets/R/Genotype96
mkdir ./Data/Real_Data/Quartets/C/Genotype97
echo '4'>>./Data/Real_Data/Quartets/C/Genotype97.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype97.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype97
mkdir ./Data/Real_Data/Quartets/R/Genotype97
mkdir ./Data/Real_Data/Quartets/C/Genotype98
echo '4'>>./Data/Real_Data/Quartets/C/Genotype98.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype98.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype98
mkdir ./Data/Real_Data/Quartets/R/Genotype98
mkdir ./Data/Real_Data/Quartets/C/Genotype99
echo '4'>>./Data/Real_Data/Quartets/C/Genotype99.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype99.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype99
mkdir ./Data/Real_Data/Quartets/R/Genotype99
mkdir ./Data/Real_Data/Quartets/C/Genotype100
echo '4'>>./Data/Real_Data/Quartets/C/Genotype100.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype100.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype100
mkdir ./Data/Real_Data/Quartets/R/Genotype100
mkdir ./Data/Real_Data/Quartets/C/Genotype101
echo '4'>>./Data/Real_Data/Quartets/C/Genotype101.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype101.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype101
mkdir ./Data/Real_Data/Quartets/R/Genotype101
mkdir ./Data/Real_Data/Quartets/C/Genotype102
echo '4'>>./Data/Real_Data/Quartets/C/Genotype102.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype102.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype102
mkdir ./Data/Real_Data/Quartets/R/Genotype102
mkdir ./Data/Real_Data/Quartets/C/Genotype103
echo '4'>>./Data/Real_Data/Quartets/C/Genotype103.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype103.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype103
mkdir ./Data/Real_Data/Quartets/R/Genotype103
mkdir ./Data/Real_Data/Quartets/C/Genotype104
echo '4'>>./Data/Real_Data/Quartets/C/Genotype104.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype104.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype104
mkdir ./Data/Real_Data/Quartets/R/Genotype104
mkdir ./Data/Real_Data/Quartets/C/Genotype105
echo '4'>>./Data/Real_Data/Quartets/C/Genotype105.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype105.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype105
mkdir ./Data/Real_Data/Quartets/R/Genotype105
mkdir ./Data/Real_Data/Quartets/C/Genotype106
echo '4'>>./Data/Real_Data/Quartets/C/Genotype106.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype106.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype106
mkdir ./Data/Real_Data/Quartets/R/Genotype106
mkdir ./Data/Real_Data/Quartets/C/Genotype107
echo '4'>>./Data/Real_Data/Quartets/C/Genotype107.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype107.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype107
mkdir ./Data/Real_Data/Quartets/R/Genotype107
mkdir ./Data/Real_Data/Quartets/C/Genotype108
echo '4'>>./Data/Real_Data/Quartets/C/Genotype108.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype108.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype108
mkdir ./Data/Real_Data/Quartets/R/Genotype108
mkdir ./Data/Real_Data/Quartets/C/Genotype109
echo '4'>>./Data/Real_Data/Quartets/C/Genotype109.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype109.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype109
mkdir ./Data/Real_Data/Quartets/R/Genotype109
mkdir ./Data/Real_Data/Quartets/C/Genotype110
echo '4'>>./Data/Real_Data/Quartets/C/Genotype110.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype110.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype110
mkdir ./Data/Real_Data/Quartets/R/Genotype110
mkdir ./Data/Real_Data/Quartets/C/Genotype111
echo '4'>>./Data/Real_Data/Quartets/C/Genotype111.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype111.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype111
mkdir ./Data/Real_Data/Quartets/R/Genotype111
mkdir ./Data/Real_Data/Quartets/C/Genotype112
echo '4'>>./Data/Real_Data/Quartets/C/Genotype112.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype112.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype112
mkdir ./Data/Real_Data/Quartets/R/Genotype112
mkdir ./Data/Real_Data/Quartets/C/Genotype113
echo '4'>>./Data/Real_Data/Quartets/C/Genotype113.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype113.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype113
mkdir ./Data/Real_Data/Quartets/R/Genotype113
mkdir ./Data/Real_Data/Quartets/C/Genotype114
echo '4'>>./Data/Real_Data/Quartets/C/Genotype114.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype114.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype114
mkdir ./Data/Real_Data/Quartets/R/Genotype114
mkdir ./Data/Real_Data/Quartets/C/Genotype115
echo '4'>>./Data/Real_Data/Quartets/C/Genotype115.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype115.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype115
mkdir ./Data/Real_Data/Quartets/R/Genotype115
mkdir ./Data/Real_Data/Quartets/C/Genotype116
echo '4'>>./Data/Real_Data/Quartets/C/Genotype116.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype116.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype116
mkdir ./Data/Real_Data/Quartets/R/Genotype116
mkdir ./Data/Real_Data/Quartets/C/Genotype117
echo '4'>>./Data/Real_Data/Quartets/C/Genotype117.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype117.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype117
mkdir ./Data/Real_Data/Quartets/R/Genotype117
mkdir ./Data/Real_Data/Quartets/C/Genotype118
echo '4'>>./Data/Real_Data/Quartets/C/Genotype118.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype118.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype118
mkdir ./Data/Real_Data/Quartets/R/Genotype118
mkdir ./Data/Real_Data/Quartets/C/Genotype119
echo '4'>>./Data/Real_Data/Quartets/C/Genotype119.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype119.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype119
mkdir ./Data/Real_Data/Quartets/R/Genotype119
mkdir ./Data/Real_Data/Quartets/C/Genotype120
echo '4'>>./Data/Real_Data/Quartets/C/Genotype120.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype120.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype120
mkdir ./Data/Real_Data/Quartets/R/Genotype120
mkdir ./Data/Real_Data/Quartets/C/Genotype121
echo '4'>>./Data/Real_Data/Quartets/C/Genotype121.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype121.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype121
mkdir ./Data/Real_Data/Quartets/R/Genotype121
mkdir ./Data/Real_Data/Quartets/C/Genotype122
echo '4'>>./Data/Real_Data/Quartets/C/Genotype122.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype122.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype122
mkdir ./Data/Real_Data/Quartets/R/Genotype122
mkdir ./Data/Real_Data/Quartets/C/Genotype123
echo '4'>>./Data/Real_Data/Quartets/C/Genotype123.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype123.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype123
mkdir ./Data/Real_Data/Quartets/R/Genotype123
mkdir ./Data/Real_Data/Quartets/C/Genotype124
echo '4'>>./Data/Real_Data/Quartets/C/Genotype124.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype124.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype124
mkdir ./Data/Real_Data/Quartets/R/Genotype124
mkdir ./Data/Real_Data/Quartets/C/Genotype125
echo '4'>>./Data/Real_Data/Quartets/C/Genotype125.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype125.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype125
mkdir ./Data/Real_Data/Quartets/R/Genotype125
mkdir ./Data/Real_Data/Quartets/C/Genotype126
echo '4'>>./Data/Real_Data/Quartets/C/Genotype126.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype126.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype126
mkdir ./Data/Real_Data/Quartets/R/Genotype126
mkdir ./Data/Real_Data/Quartets/C/Genotype127
echo '4'>>./Data/Real_Data/Quartets/C/Genotype127.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype127.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype127
mkdir ./Data/Real_Data/Quartets/R/Genotype127
mkdir ./Data/Real_Data/Quartets/C/Genotype128
echo '4'>>./Data/Real_Data/Quartets/C/Genotype128.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype128.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype128
mkdir ./Data/Real_Data/Quartets/R/Genotype128
mkdir ./Data/Real_Data/Quartets/C/Genotype129
echo '4'>>./Data/Real_Data/Quartets/C/Genotype129.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype129.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype129
mkdir ./Data/Real_Data/Quartets/R/Genotype129
mkdir ./Data/Real_Data/Quartets/C/Genotype130
echo '4'>>./Data/Real_Data/Quartets/C/Genotype130.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype130.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype130
mkdir ./Data/Real_Data/Quartets/R/Genotype130
mkdir ./Data/Real_Data/Quartets/C/Genotype131
echo '4'>>./Data/Real_Data/Quartets/C/Genotype131.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype131.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype131
mkdir ./Data/Real_Data/Quartets/R/Genotype131
mkdir ./Data/Real_Data/Quartets/C/Genotype132
echo '4'>>./Data/Real_Data/Quartets/C/Genotype132.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype132.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype132
mkdir ./Data/Real_Data/Quartets/R/Genotype132
mkdir ./Data/Real_Data/Quartets/C/Genotype133
echo '4'>>./Data/Real_Data/Quartets/C/Genotype133.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype133.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype133
mkdir ./Data/Real_Data/Quartets/R/Genotype133
mkdir ./Data/Real_Data/Quartets/C/Genotype134
echo '4'>>./Data/Real_Data/Quartets/C/Genotype134.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype134.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype134
mkdir ./Data/Real_Data/Quartets/R/Genotype134
mkdir ./Data/Real_Data/Quartets/C/Genotype135
echo '4'>>./Data/Real_Data/Quartets/C/Genotype135.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype135.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype135
mkdir ./Data/Real_Data/Quartets/R/Genotype135
mkdir ./Data/Real_Data/Quartets/C/Genotype136
echo '4'>>./Data/Real_Data/Quartets/C/Genotype136.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype136.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype136
mkdir ./Data/Real_Data/Quartets/R/Genotype136
mkdir ./Data/Real_Data/Quartets/C/Genotype137
echo '4'>>./Data/Real_Data/Quartets/C/Genotype137.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype137.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype137
mkdir ./Data/Real_Data/Quartets/R/Genotype137
mkdir ./Data/Real_Data/Quartets/C/Genotype138
echo '4'>>./Data/Real_Data/Quartets/C/Genotype138.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype138.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype138
mkdir ./Data/Real_Data/Quartets/R/Genotype138
mkdir ./Data/Real_Data/Quartets/C/Genotype139
echo '4'>>./Data/Real_Data/Quartets/C/Genotype139.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype139.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype139
mkdir ./Data/Real_Data/Quartets/R/Genotype139
mkdir ./Data/Real_Data/Quartets/C/Genotype140
echo '4'>>./Data/Real_Data/Quartets/C/Genotype140.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype140.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype140
mkdir ./Data/Real_Data/Quartets/R/Genotype140
mkdir ./Data/Real_Data/Quartets/C/Genotype141
echo '4'>>./Data/Real_Data/Quartets/C/Genotype141.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype141.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype141
mkdir ./Data/Real_Data/Quartets/R/Genotype141
mkdir ./Data/Real_Data/Quartets/C/Genotype142
echo '4'>>./Data/Real_Data/Quartets/C/Genotype142.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype142.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype142
mkdir ./Data/Real_Data/Quartets/R/Genotype142
mkdir ./Data/Real_Data/Quartets/C/Genotype143
echo '4'>>./Data/Real_Data/Quartets/C/Genotype143.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype143.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype143
mkdir ./Data/Real_Data/Quartets/R/Genotype143
mkdir ./Data/Real_Data/Quartets/C/Genotype144
echo '4'>>./Data/Real_Data/Quartets/C/Genotype144.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype144.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype144
mkdir ./Data/Real_Data/Quartets/R/Genotype144
mkdir ./Data/Real_Data/Quartets/C/Genotype145
echo '4'>>./Data/Real_Data/Quartets/C/Genotype145.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype145.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype145
mkdir ./Data/Real_Data/Quartets/R/Genotype145
mkdir ./Data/Real_Data/Quartets/C/Genotype146
echo '4'>>./Data/Real_Data/Quartets/C/Genotype146.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype146.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype146
mkdir ./Data/Real_Data/Quartets/R/Genotype146
mkdir ./Data/Real_Data/Quartets/C/Genotype147
echo '4'>>./Data/Real_Data/Quartets/C/Genotype147.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype147.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype147
mkdir ./Data/Real_Data/Quartets/R/Genotype147
mkdir ./Data/Real_Data/Quartets/C/Genotype148
echo '4'>>./Data/Real_Data/Quartets/C/Genotype148.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype148.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype148
mkdir ./Data/Real_Data/Quartets/R/Genotype148
mkdir ./Data/Real_Data/Quartets/C/Genotype149
echo '4'>>./Data/Real_Data/Quartets/C/Genotype149.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype149.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype149
mkdir ./Data/Real_Data/Quartets/R/Genotype149
mkdir ./Data/Real_Data/Quartets/C/Genotype150
echo '4'>>./Data/Real_Data/Quartets/C/Genotype150.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype150.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype150
mkdir ./Data/Real_Data/Quartets/R/Genotype150
mkdir ./Data/Real_Data/Quartets/C/Genotype151
echo '4'>>./Data/Real_Data/Quartets/C/Genotype151.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype151.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype151
mkdir ./Data/Real_Data/Quartets/R/Genotype151
mkdir ./Data/Real_Data/Quartets/C/Genotype152
echo '4'>>./Data/Real_Data/Quartets/C/Genotype152.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype152.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype152
mkdir ./Data/Real_Data/Quartets/R/Genotype152
mkdir ./Data/Real_Data/Quartets/C/Genotype153
echo '4'>>./Data/Real_Data/Quartets/C/Genotype153.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype153.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype153
mkdir ./Data/Real_Data/Quartets/R/Genotype153
mkdir ./Data/Real_Data/Quartets/C/Genotype154
echo '4'>>./Data/Real_Data/Quartets/C/Genotype154.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype154.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype154
mkdir ./Data/Real_Data/Quartets/R/Genotype154
mkdir ./Data/Real_Data/Quartets/C/Genotype155
echo '4'>>./Data/Real_Data/Quartets/C/Genotype155.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype155.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype155
mkdir ./Data/Real_Data/Quartets/R/Genotype155
mkdir ./Data/Real_Data/Quartets/C/Genotype156
echo '4'>>./Data/Real_Data/Quartets/C/Genotype156.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype156.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype156
mkdir ./Data/Real_Data/Quartets/R/Genotype156
mkdir ./Data/Real_Data/Quartets/C/Genotype157
echo '4'>>./Data/Real_Data/Quartets/C/Genotype157.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype157.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype157
mkdir ./Data/Real_Data/Quartets/R/Genotype157
mkdir ./Data/Real_Data/Quartets/C/Genotype158
echo '4'>>./Data/Real_Data/Quartets/C/Genotype158.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype158.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype158
mkdir ./Data/Real_Data/Quartets/R/Genotype158
mkdir ./Data/Real_Data/Quartets/C/Genotype159
echo '4'>>./Data/Real_Data/Quartets/C/Genotype159.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype159.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype159
mkdir ./Data/Real_Data/Quartets/R/Genotype159
mkdir ./Data/Real_Data/Quartets/C/Genotype160
echo '4'>>./Data/Real_Data/Quartets/C/Genotype160.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype160.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype160
mkdir ./Data/Real_Data/Quartets/R/Genotype160
mkdir ./Data/Real_Data/Quartets/C/Genotype161
echo '4'>>./Data/Real_Data/Quartets/C/Genotype161.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype161.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype161
mkdir ./Data/Real_Data/Quartets/R/Genotype161
mkdir ./Data/Real_Data/Quartets/C/Genotype162
echo '4'>>./Data/Real_Data/Quartets/C/Genotype162.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype162.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype162
mkdir ./Data/Real_Data/Quartets/R/Genotype162
mkdir ./Data/Real_Data/Quartets/C/Genotype163
echo '4'>>./Data/Real_Data/Quartets/C/Genotype163.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype163.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype163
mkdir ./Data/Real_Data/Quartets/R/Genotype163
mkdir ./Data/Real_Data/Quartets/C/Genotype164
echo '4'>>./Data/Real_Data/Quartets/C/Genotype164.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype164.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype164
mkdir ./Data/Real_Data/Quartets/R/Genotype164
mkdir ./Data/Real_Data/Quartets/C/Genotype165
echo '4'>>./Data/Real_Data/Quartets/C/Genotype165.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype165.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype165
mkdir ./Data/Real_Data/Quartets/R/Genotype165
mkdir ./Data/Real_Data/Quartets/C/Genotype166
echo '4'>>./Data/Real_Data/Quartets/C/Genotype166.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype166.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype166
mkdir ./Data/Real_Data/Quartets/R/Genotype166
mkdir ./Data/Real_Data/Quartets/C/Genotype167
echo '4'>>./Data/Real_Data/Quartets/C/Genotype167.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype167.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype167
mkdir ./Data/Real_Data/Quartets/R/Genotype167
mkdir ./Data/Real_Data/Quartets/C/Genotype168
echo '4'>>./Data/Real_Data/Quartets/C/Genotype168.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype168.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype168
mkdir ./Data/Real_Data/Quartets/R/Genotype168
mkdir ./Data/Real_Data/Quartets/C/Genotype169
echo '4'>>./Data/Real_Data/Quartets/C/Genotype169.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype169.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype169
mkdir ./Data/Real_Data/Quartets/R/Genotype169
mkdir ./Data/Real_Data/Quartets/C/Genotype170
echo '4'>>./Data/Real_Data/Quartets/C/Genotype170.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype170.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype170
mkdir ./Data/Real_Data/Quartets/R/Genotype170
mkdir ./Data/Real_Data/Quartets/C/Genotype171
echo '4'>>./Data/Real_Data/Quartets/C/Genotype171.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype171.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype171
mkdir ./Data/Real_Data/Quartets/R/Genotype171
mkdir ./Data/Real_Data/Quartets/C/Genotype172
echo '4'>>./Data/Real_Data/Quartets/C/Genotype172.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype172.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype172
mkdir ./Data/Real_Data/Quartets/R/Genotype172
mkdir ./Data/Real_Data/Quartets/C/Genotype173
echo '4'>>./Data/Real_Data/Quartets/C/Genotype173.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype173.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype173
mkdir ./Data/Real_Data/Quartets/R/Genotype173
mkdir ./Data/Real_Data/Quartets/C/Genotype174
echo '4'>>./Data/Real_Data/Quartets/C/Genotype174.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype174.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype174
mkdir ./Data/Real_Data/Quartets/R/Genotype174
mkdir ./Data/Real_Data/Quartets/C/Genotype175
echo '4'>>./Data/Real_Data/Quartets/C/Genotype175.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype175.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype175
mkdir ./Data/Real_Data/Quartets/R/Genotype175
mkdir ./Data/Real_Data/Quartets/C/Genotype176
echo '4'>>./Data/Real_Data/Quartets/C/Genotype176.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype176.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype176
mkdir ./Data/Real_Data/Quartets/R/Genotype176
mkdir ./Data/Real_Data/Quartets/C/Genotype177
echo '4'>>./Data/Real_Data/Quartets/C/Genotype177.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype177.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype177
mkdir ./Data/Real_Data/Quartets/R/Genotype177
mkdir ./Data/Real_Data/Quartets/C/Genotype178
echo '4'>>./Data/Real_Data/Quartets/C/Genotype178.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype178.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype178
mkdir ./Data/Real_Data/Quartets/R/Genotype178
mkdir ./Data/Real_Data/Quartets/C/Genotype179
echo '4'>>./Data/Real_Data/Quartets/C/Genotype179.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype179.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype179
mkdir ./Data/Real_Data/Quartets/R/Genotype179
mkdir ./Data/Real_Data/Quartets/C/Genotype180
echo '4'>>./Data/Real_Data/Quartets/C/Genotype180.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype180.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype180
mkdir ./Data/Real_Data/Quartets/R/Genotype180
mkdir ./Data/Real_Data/Quartets/C/Genotype181
echo '4'>>./Data/Real_Data/Quartets/C/Genotype181.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype181.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype181
mkdir ./Data/Real_Data/Quartets/R/Genotype181
mkdir ./Data/Real_Data/Quartets/C/Genotype182
echo '4'>>./Data/Real_Data/Quartets/C/Genotype182.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype182.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype182
mkdir ./Data/Real_Data/Quartets/R/Genotype182
mkdir ./Data/Real_Data/Quartets/C/Genotype183
echo '4'>>./Data/Real_Data/Quartets/C/Genotype183.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype183.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype183
mkdir ./Data/Real_Data/Quartets/R/Genotype183
mkdir ./Data/Real_Data/Quartets/C/Genotype184
echo '4'>>./Data/Real_Data/Quartets/C/Genotype184.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype184.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype184
mkdir ./Data/Real_Data/Quartets/R/Genotype184
mkdir ./Data/Real_Data/Quartets/C/Genotype185
echo '4'>>./Data/Real_Data/Quartets/C/Genotype185.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype185.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype185
mkdir ./Data/Real_Data/Quartets/R/Genotype185
mkdir ./Data/Real_Data/Quartets/C/Genotype186
echo '4'>>./Data/Real_Data/Quartets/C/Genotype186.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype186.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype186
mkdir ./Data/Real_Data/Quartets/R/Genotype186
mkdir ./Data/Real_Data/Quartets/C/Genotype187
echo '4'>>./Data/Real_Data/Quartets/C/Genotype187.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype187.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype187
mkdir ./Data/Real_Data/Quartets/R/Genotype187
mkdir ./Data/Real_Data/Quartets/C/Genotype188
echo '4'>>./Data/Real_Data/Quartets/C/Genotype188.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype188.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype188
mkdir ./Data/Real_Data/Quartets/R/Genotype188
mkdir ./Data/Real_Data/Quartets/C/Genotype189
echo '4'>>./Data/Real_Data/Quartets/C/Genotype189.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype189.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype189
mkdir ./Data/Real_Data/Quartets/R/Genotype189
mkdir ./Data/Real_Data/Quartets/C/Genotype190
echo '4'>>./Data/Real_Data/Quartets/C/Genotype190.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype190.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype190
mkdir ./Data/Real_Data/Quartets/R/Genotype190
mkdir ./Data/Real_Data/Quartets/C/Genotype191
echo '4'>>./Data/Real_Data/Quartets/C/Genotype191.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype191.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype191
mkdir ./Data/Real_Data/Quartets/R/Genotype191
mkdir ./Data/Real_Data/Quartets/C/Genotype192
echo '4'>>./Data/Real_Data/Quartets/C/Genotype192.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype192.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype192
mkdir ./Data/Real_Data/Quartets/R/Genotype192
mkdir ./Data/Real_Data/Quartets/C/Genotype193
echo '4'>>./Data/Real_Data/Quartets/C/Genotype193.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype193.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype193
mkdir ./Data/Real_Data/Quartets/R/Genotype193
mkdir ./Data/Real_Data/Quartets/C/Genotype194
echo '4'>>./Data/Real_Data/Quartets/C/Genotype194.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype194.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype194
mkdir ./Data/Real_Data/Quartets/R/Genotype194
mkdir ./Data/Real_Data/Quartets/C/Genotype195
echo '4'>>./Data/Real_Data/Quartets/C/Genotype195.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype195.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype195
mkdir ./Data/Real_Data/Quartets/R/Genotype195
mkdir ./Data/Real_Data/Quartets/C/Genotype196
echo '4'>>./Data/Real_Data/Quartets/C/Genotype196.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype196.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype196
mkdir ./Data/Real_Data/Quartets/R/Genotype196
mkdir ./Data/Real_Data/Quartets/C/Genotype197
echo '4'>>./Data/Real_Data/Quartets/C/Genotype197.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype197.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype197
mkdir ./Data/Real_Data/Quartets/R/Genotype197
mkdir ./Data/Real_Data/Quartets/C/Genotype198
echo '4'>>./Data/Real_Data/Quartets/C/Genotype198.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype198.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype198
mkdir ./Data/Real_Data/Quartets/R/Genotype198
mkdir ./Data/Real_Data/Quartets/C/Genotype199
echo '4'>>./Data/Real_Data/Quartets/C/Genotype199.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype199.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype199
mkdir ./Data/Real_Data/Quartets/R/Genotype199
mkdir ./Data/Real_Data/Quartets/C/Genotype200
echo '4'>>./Data/Real_Data/Quartets/C/Genotype200.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype200.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype200
mkdir ./Data/Real_Data/Quartets/R/Genotype200
mkdir ./Data/Real_Data/Quartets/C/Genotype201
echo '4'>>./Data/Real_Data/Quartets/C/Genotype201.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype201.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype201
mkdir ./Data/Real_Data/Quartets/R/Genotype201
mkdir ./Data/Real_Data/Quartets/C/Genotype202
echo '4'>>./Data/Real_Data/Quartets/C/Genotype202.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype202.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype202
mkdir ./Data/Real_Data/Quartets/R/Genotype202
mkdir ./Data/Real_Data/Quartets/C/Genotype203
echo '4'>>./Data/Real_Data/Quartets/C/Genotype203.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype203.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype203
mkdir ./Data/Real_Data/Quartets/R/Genotype203
mkdir ./Data/Real_Data/Quartets/C/Genotype204
echo '4'>>./Data/Real_Data/Quartets/C/Genotype204.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype204.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype204
mkdir ./Data/Real_Data/Quartets/R/Genotype204
mkdir ./Data/Real_Data/Quartets/C/Genotype205
echo '4'>>./Data/Real_Data/Quartets/C/Genotype205.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype205.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype205
mkdir ./Data/Real_Data/Quartets/R/Genotype205
mkdir ./Data/Real_Data/Quartets/C/Genotype206
echo '4'>>./Data/Real_Data/Quartets/C/Genotype206.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype206.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype206
mkdir ./Data/Real_Data/Quartets/R/Genotype206
mkdir ./Data/Real_Data/Quartets/C/Genotype207
echo '4'>>./Data/Real_Data/Quartets/C/Genotype207.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype207.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype207
mkdir ./Data/Real_Data/Quartets/R/Genotype207
mkdir ./Data/Real_Data/Quartets/C/Genotype208
echo '4'>>./Data/Real_Data/Quartets/C/Genotype208.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype208.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype208
mkdir ./Data/Real_Data/Quartets/R/Genotype208
mkdir ./Data/Real_Data/Quartets/C/Genotype209
echo '4'>>./Data/Real_Data/Quartets/C/Genotype209.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype209.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype209
mkdir ./Data/Real_Data/Quartets/R/Genotype209
mkdir ./Data/Real_Data/Quartets/C/Genotype210
echo '4'>>./Data/Real_Data/Quartets/C/Genotype210.poset
echo '0'>>./Data/Real_Data/Quartets/C/Genotype210.poset
mkdir ./Data/Real_Data/Quartets/H/Genotype210
mkdir ./Data/Real_Data/Quartets/R/Genotype210
