Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 1
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 2
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 3
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 4
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 5
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 6
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 7
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 8
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 9
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 10
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 11
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 12
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 13
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 14
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 15
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 16
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 17
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 18
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 19
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 20
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 21
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 22
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 23
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 24
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 25
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 26
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 27
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 28
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 29
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 30
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 31
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 32
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 33
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 34
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 35
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 36
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 37
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 38
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 39
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 40
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 41
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 42
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 43
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 44
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 45
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 46
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 47
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 48
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 49
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 50
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 51
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 52
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 53
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 54
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 55
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 56
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 57
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 58
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 59
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 60
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 61
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 62
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 63
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 64
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 65
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 66
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 67
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 68
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 69
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 70
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 71
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 72
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 73
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 74
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 75
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 76
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 77
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 78
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 79
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 80
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 81
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 82
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 83
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 84
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 85
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 86
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 87
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 88
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 89
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 90
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 91
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 92
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 93
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 94
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 95
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 96
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 97
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 98
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 99
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 100
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 101
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 102
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 103
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 104
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 105
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 106
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 107
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 108
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 109
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 110
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 111
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 112
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 113
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 114
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 115
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 116
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 117
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 118
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 119
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 120
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 121
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 122
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 123
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 124
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 125
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 126
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 127
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 128
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 129
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 130
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 131
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 132
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 133
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 134
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 135
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 136
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 137
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 138
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 139
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 140
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 141
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 142
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 143
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 144
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 145
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 146
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 147
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 148
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 149
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 150
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 151
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 152
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 153
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 154
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 155
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 156
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 157
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 158
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 159
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 160
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 161
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 162
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 163
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 164
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 165
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 166
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 167
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 168
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 169
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 170
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 171
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 172
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 173
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 174
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 175
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 176
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 177
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 178
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 179
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 180
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 181
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 182
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 183
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 184
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 185
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 186
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 187
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 188
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 189
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 190
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 191
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 192
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 193
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 194
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 195
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 196
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 197
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 198
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 199
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 200
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 201
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 202
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 203
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 204
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 205
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 206
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 207
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 208
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 209
Rscript --vanilla ./Codes/QuartetCBN/Step4B.R 210
